"""Add Review Model

Revision ID: 8d9e29809882
Revises: 22137bdc64d5
Create Date: 2023-07-14 13:44:20.053294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9e29809882'
down_revision = '22137bdc64d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
