"""Add Review Model

Revision ID: 9e45065a68b7
Revises: 8d9e29809882
Create Date: 2023-07-14 13:44:47.269739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e45065a68b7'
down_revision = '8d9e29809882'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
